---
  title: "economy_SHAB"
output: html_document
---

###DIESES SKRIPT LÄUFT NICHT OHNE ZUGANG ZUR MONEYHOUSE API###
  
```{r setup, include=FALSE}
rm(list=ls())
knitr::opts_chunk$set(echo = TRUE)

library('httr')
library('jsonlite')
library('dplyr')
library('tidyverse')
library('plotly')

# Verbindungsinfos
source("mhouse_connect.r") #-> File mit Zugangsdaten. Kann nicht öffentlich gemacht werden

```

```{r Erstellen des Anfangsdatensatzes,echo=FALSE}
##1. Jahr
#startdate <- '2015-01-01'
#enddate <- '2015-12-31'
#categories <- c(2,3) #See data frame publikat, Categorie 31 gehört wohl zu den Konkursämtern
#cats <- paste0('&category=',categories, collapse='')
#call1 <- paste0(base,"publication?from=",startdate,'&to=',enddate,cats)
#entriescall <- GET(call1, add_headers(`user-key`=user_key))
#entries <- content(entriescall,'text')
#entries <- jsonlite::fromJSON(entries, flatten = TRUE)
#
##2. Die weiteren Jahre
#jahre <- data.frame(start = c('2016-01-01',
#                              '2017-01-01',
#                              '2018-01-01',
#                              '2019-01-01',
#                              '2020-01-01'),
#                    ende = c('2016-12-31',
#                             '2017-12-31',
#                             '2018-12-31',
#                             '2019-12-31',
#                             '2020-12-31'))
#
#for (i in c(1:dim(jahre)[1])){
#  
#startdate <- jahre$start[i]
#enddate <- jahre$ende[i]
#cats <- paste0('&category=',categories, collapse='')
#categories <- c(2,3) #See data frame publikat, Categorie 31 gehört wohl zu den Konkursämtern
#call1 <- paste0(base,"publication?from=",startdate,'&to=',enddate,cats)
#entriescall <- GET(call1,
#add_headers(`user-key`=user_key))
#entries_temp <- content(entriescall,'text')
#entries_temp <- jsonlite::fromJSON(entries_temp, flatten = TRUE)
#entries <- rbind(entries,entries_temp)
#}
#rm(entries_temp)
```

```{r Datensatz um neue Tage ergänzen}
##################
#Neue Daten laden#
##################
konk_prev <- readRDS('...') #-> Dieser Datensatz kann nicht öffentlich gemacht werden. Er enthält die einzelnen Meldungen.

startdate <- max(as.Date(konk_prev$date))+1
enddate <- Sys.Date()-1

categories <- c(2,3) #See data frame publikat, Categorie 31 gehört wohl zu den Konkursämtern
cats <- paste0('&category=',categories, collapse='')
call1 <- paste0(base,"publication?from=",startdate,'&to=',enddate,cats)
entriescall <- GET(call1,
add_headers(`user-key`=user_key))
entries <- content(entriescall,'text')
entries <- jsonlite::fromJSON(entries, flatten = TRUE)

#Firmen mit Organisationsmängel oder mangelndem Domizil rausfiltern 
entries$orgmangel <- grepl(c('731b'),entries$text) #|153b
entries$orgmangel <- ifelse(entries$orgmangel == TRUE, 1, 0)

#Mehrwertsteuernummer rausfiltern
entries$uid <- str_extract(entries$text,  regex("CHE-(\\d{3})\\.(\\d{3})\\.(\\d{3})")) #Achtung: Es werden nur Firmen erfasst, keine Administrativeinheiten (deren Nummber beginnt mit ADM)

#Datums und Jahresvariable
entries$date<-as.Date(entries$date)
entries$year <- as.numeric(substring(entries$date,1,4))

#Test:  keine gleichen IDs
table(entries$id %in% konk_prev$id)

#Firmen die schon mal erfasst sind kommen raus
entries <- entries[!entries$id %in% konk_prev$id,]
entries <- entries[!entries$uid %in% konk_prev$uid,]
```

```{r Konkursmeldungen}
konk <- entries %>%
  filter(map_lgl(categories, ~'3' %in% .))

#Mehrfaches Vorkommen von Firmen
#ee<-data.frame(table(konk$companyId))
#konk<-base::merge(konk, ee, by.x="companyId", by.y="Var1", all.x=T)
#table(konk$Freq)

#absteigend sortieren
konk<- konk[order(konk$date, decreasing=F),]

#nur der erste firmenbezogeneeintrag bleibt drin 
konk<-subset(konk, duplicated(konk$companyId)==F) 

#Meldungen: 
konkmeld <-  konk$id


```

```{r Liquidatonen}
liq <- entries %>%
  filter(map_lgl(categories, ~'2' %in% .))%>%
  filter(orgmangel ==1)%>%
  filter(!id %in% konkmeld)


#absteigend sortieren, und ersten Eintrag behalten
liq<- liq[order(liq$date, decreasing=F),]
liq<-subset(liq, duplicated(liq$companyId)==F) 

```

```{r Abgeleich Konkurse und Liquidationen}
liq$date_liq <- liq$date
liq$shabPdfLink_liq <- liq$shabPdfLink
liq$text_liq <- liq$text
liq$categories_liq <- liq$categories

#Konkurserföffnunge wegen Orgmangel, nicht als Eröffnung sondern etwas anderes erfasst sind:
vgl1 <- base::merge(konk,liq[,c('uid','date_liq','text_liq','shabPdfLink_liq','categories_liq')], by=c('uid'),all.x=T, all.y=F)

vgl_falschkonk <- vgl1%>%
  filter(!is.na(date_liq))%>%
  filter(date >= date_liq)

#1. Löschen der falsch erfassten Konkurseeröffnungen
konk <- konk[!konk$id %in% vgl_falschkonk$id,]

#2. Ergänzen, um die noch nicht erfasste 713b-Eröffnungen
liq$date_liq <- NULL
liq$shabPdfLink_liq <- NULL
liq$text_liq <- NULL
liq$categories_liq <- NULL

liq_lagged <- vgl1%>%
  filter(!is.na(date_liq))%>%
  filter(date < date_liq)

liq <- liq[!liq$id %in% liq_lagged$id,]

#Meldungen Konkurse
konk <- rbind(konk,liq)

#Alten Datensatz abspeichern
konk$persons <- NULL
konk$commercialRegisterNumber <- NULL

konk_prev <- rbind(konk_prev,konk)

table(duplicated(konk_prev$id))
table(duplicated(konk_prev$uid))

konk_prev<- konk_prev[order(konk_prev$date, decreasing=F),]
konk_prev<- subset(konk_prev, duplicated(konk_prev$uid)==F) 

saveRDS(konk_prev, file="...")
```

```{r Datensatz speichern,echo=FALSE}
df_cant <- konk_prev %>%
  filter(date>=as.Date('2017-01-01'))%>%
  mutate(commercialRegistercanton = as.factor(commercialRegistercanton),
         orgmangel = as.factor(orgmangel))%>%
  group_by(date,commercialRegistercanton,orgmangel, .drop=F)%>%
  summarise(value = n())%>%
  rename(location = commercialRegistercanton)%>%
  mutate(variable_short = ifelse(orgmangel==0,'konk_eroeff','mangel_eroeff'),
         variable_long = ifelse(orgmangel==0,'Eröffnung erstmaliger Konkursverfahren','Erstmalige Eröffnungen eines Konkursverfahrens wegen organisatorischer Mängel'))

df_ch <- konk_prev %>%
  filter(date>=as.Date('2017-01-01'))%>%
  group_by(date,orgmangel)%>%
  summarise(value = n())%>%
  mutate(location = 'CH')%>%
  mutate(variable_short = ifelse(orgmangel==0,'konk_eroeff','mangel_eroeff'),
         variable_long = ifelse(orgmangel==0,'Anzahl Eröffnungen erstmaliger Konkursverfahren (exkl. Verfahren nach Art. 731b OR)','Erstmalige Eröffnungen eines Konkursverfahrens wegen organisatorischer Mängel'))

Economy_SHAB <- df_cant%>%
  filter(variable_short == 'konk_eroeff')%>%
  mutate(topic = 'Wirtschaft',
         unit = 'Anzahl',
         source = 'SHAB via Moneyhouse API',
         update = 'täglich',
         public = 'ja',
         description = 'https://github.com/statistikZH/economy_SHAB') %>%
  select(date,value,topic,variable_short,variable_long,location,unit,source,update,public,description)

#Private
write.csv(Economy_SHAB,'~/covid19monitoring_server/economy_SHAB_private/Economy_SHAB.csv',row.names=F, fileEncoding = "UTF-8")
#Öffentlich
write.csv(Economy_SHAB,'~/covid19monitoring_server/economy_SHAB/Economy_SHAB.csv',row.names=F, fileEncoding = "UTF-8")
```

```{r Grafische Darstellung Absolute Zahlen: Schweiz,echo=FALSE}
lastmon <- function(x) 7 * floor(as.numeric(x-1+4)/7) + as.Date(1-4, origin="1970-01-01")

df_ch$monday <- lastmon(df_ch$date)
df_ch$week <- lubridate::isoweek(df_ch$date)

pldf <- df_ch%>%
  filter(location=='CH')%>%
  mutate(year = substring(date,1,4))%>%
  mutate(orgmangel = ifelse(grepl('liq_',variable_short),'orgmangel','konkurs'))%>%
  mutate(week = lubridate::isoweek(date))%>%
  filter(orgmangel=='konkurs')%>%
  group_by(year,week,monday)%>%
  summarise(value = sum(value))%>%
  mutate(zvalue = (value-mean(value))/sd(value))

p_ch <- ggplot(pldf,aes(week,value)) +
  geom_col(aes(text=sprintf("Woche: %s<br>Eröffnungen: %s<br>Montag der Woche:%s", week, value,monday)))+
  facet_wrap(~year)

plotly::ggplotly(p_ch, tooltip="text")

```

```{r Grafische Darstellung Absolute Zahlen: Kantone,echo=FALSE}
pldf <- Economy_SHAB%>%
  mutate(monday = lastmon(date))%>%
  filter(location!='CH')%>%
  mutate(year = substring(date,1,4))%>%
  mutate(orgmangel = ifelse(grepl('liq_',variable_short),'orgmangel','konkurs'))%>%
  mutate(week = lubridate::isoweek(date))%>%
  filter(orgmangel=='konkurs')%>%
  group_by(location,year,week,monday)%>%
  summarise(value = sum(value))%>%
  ungroup()%>%
  group_by(location)%>%
  mutate(zvalue = (value-mean(value))/sd(value))

p_cant <- ggplot(pldf,aes(monday,value)) +
  geom_col(aes(text=sprintf("Woche: %s<br>Eröffnungen: %s<br>Montag der Woche:%s", week, value,monday)))+
  facet_wrap(~location)

plotly::ggplotly(p_cant, tooltip="text")

```

```{r Grafische Darstellung z-Zahlen: Kantone,echo=FALSE}

p_cantz <- ggplot(pldf,aes(monday,zvalue)) +
  geom_col(aes(text=sprintf("Woche: %s<br>Eröffnungen: %s<br>Montag der Woche:%s", week, value,monday)))+
  facet_wrap(~location)

plotly::ggplotly(p_cantz, tooltip="text")


pldf <- Economy_SHAB%>%
  filter(location!='CH')%>%
  mutate(year = substring(date,1,4))%>%
  mutate(orgmangel = ifelse(grepl('liq_',variable_short),'orgmangel','konkurs'))%>%
  mutate(week = lubridate::isoweek(date))%>%
  filter(orgmangel=='konkurs')%>%
  group_by(location,year)%>%
  summarise(count = n())

table(pldf$location)

```



```{r Daten mit Zürich vergleichen,echo=FALSE}
#getwd()
zh_full <- read.csv('../Economy_HRA_eroeff.csv')%>%
  mutate(date = as.Date(DATUM_TB),
         year =substring(DATUM_TB,1,4))%>%
  filter(year>=2017)
#
max(as.Date(zh_full$DATUM_TB))
#  
zh_api_full <- konk1520def[konk1520def$commercialRegistercanton=='ZH' & konk1520def$date>='2017-01-01'& konk1520def$date<=max(as.Date(zh_full$DATUM_TB)) & konk1520def$orgmangel==0,]
#
zh_api_full$UID_NUMBER <- gsub('-','',zh_api_full$uid, fixed=T)
zh_api_full$UID_NUMBER <- gsub('.','',zh_api_full$UID_NUMBER , fixed=T)
#

#
table(zh_full$UID_NUMMER %in% zh_api_full$UID_NUMBER)
#
table(zh_api_full$UID_NUMBER %in% zh_full$UID_NUMMER)
prop.table(table(zh_api_full$UID_NUMBER %in% zh_full$UID_NUMMER))

table(zh_full$UID_NUMMER %in% zh_api_full$UID_NUMBER)
prop.table(table(zh_full$UID_NUMMER %in% zh_api_full$UID_NUMBER))

#
View(zh_api_full[!zh_api_full$UID_NUMBER %in% zh_full$UID_NUMMER,])
#
#table(zh_api_full$categories2[!zh_api_full$UID_NUMBER %in% zh_full$UID_NUMMER])
#table(zh_api_full$categories2[zh_api_full$UID_NUMBER %in% zh_full$UID_NUMMER])
#
#https://www.shab.ch/shabforms/servlet/Search?EID=7&DOCID=4374499	
#
#
#zh <- read.csv('../Economy_HRA_eroeff.csv') %>%
#  group_by(DATUM_TB)%>%
#  summarise(value = n())%>%
#  mutate(date = as.Date(DATUM_TB),
#         year =substring(DATUM_TB,1,4))
#
#api_to_bfs <- Economy_SHAB %>%
#  mutate(year = substring(date,1,4))%>%
#  mutate(orgmangel = ifelse(grepl('liq_',variable_short),'orgmangel','konkurs'))%>%
#  mutate(location = stringr::str_sub(variable_short,-2,-1))%>%
#  group_by(year,location, orgmangel)%>%
#  summarise(Freq = sum(value)) %>%
#  #ungroup()%>%  
#  #group_by(orgmangel)%>%
#  spread(orgmangel,Freq)
#
#df_ch$year <- substring(df_ch$date,1,4)
#table(df_ch$year,df_ch$orgmangel)
#  
#
#df_cant$year <- substring(df_cant$date,1,4)
#table(df_cant$year,df_cant$orgmangel)
#
#vgldf <- df_cant %>%
#  group_by(year,location,orgmangel)%>%
#  summarise(cases = sum(value))
#
#xlsx::write.xlsx(x=as.data.frame(vgldf),file='vgldf.xlsx')
#
#df_cant %>%
#  filter(location=='ZH')%>%
#  group_by(year,orgmangel)%>%
#  summarise(caes = sum(value))
#
#table(zh$year)
#table(zh_api$year)
#
#
##Vergleich mit BSF
#
#
#
#
#pldf <- bind_rows(zh_api,zh)
#
#
#View(konk1520def[])

```


